apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-project
  template:
    metadata:
      labels:
        app: ci-cd-project
    spec:
      containers:
      - name: ci-cd-project
        image: username/ci-cd-project:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-project-service
spec:
  type: NodePort
  selector:
    app: ci-cd-project
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
